# Site settings
title: VROCK
description:
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "localhost:4000" # the base hostname & protocol for your site e.g. https://www.john-fischer.ch



# User settings
username: VROCK
user_description: "Hi, folks and welcome to my blog. I'm a passionate it technician who's always open for learning new things. So check out my work."
user_title: by Tobias Geiser
twitter_username: tobias_geiser
github_username:  tobias-geiser

# Google-analytics
#google-analytics:
#  id: "UA-132338013-1"

exclude: ['src' , 'node_modules']

remote_theme: team-vrock/jekyll-theme-vrock@v1.0.0
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - liquid_pluralize
  - liquid_reading_time


# Github settings
repository: team-vrock/team-vrock.github.io
github: [metadata]
