# Site settings
title: VROCK
description:
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br



# User settings
username: VROCK
user_description: "Hi, folks and welcome to my blog. I'm a passionated senior system engineer who's always open for learning new things. So check out my work."
user_title: by Tobias Geiser
twitter_username: tobias_geiser
github_username:  tobias-geiser

# Google-analytics
google-analytics:
  id: ""

exclude: ['src' , 'node_modules']

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

#plugins:
#  - jekyll-minifier


# Github settings
repository: public-vrock/public-vrock.github.io
github: [metadata]