# Site settings
title: VROCK
description: "A Jekyll theme for developers"
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "localhost:4000" # the base hostname & protocol for your site e.g. https://www.john-fischer.ch

# User settings
username: VROCK
user_description: "Hi, folks and welcome to my blog. I'm a passionate it technician who's always open for learning new things. So check out my work."
user_title: by Tobias Geiser
twitter_username: tobias_geiser
github_username:  tobias-geiser


# Algolia search settings
algolia:
  application_id: '601E6L68TZ'
  index_name: 'prod_web_vrock_homepage_index'
  search_only_api_key: '9cb6e240f6849ce4e240437d156ef6a2'
  powered_by: true


# Google-analytics
google-analytics:
  id: "G-TQ7CBSXT3V"

exclude: ['src' , 'node_modules']

remote_theme: team-vrock/jekyll-theme-vrock@v1.0.1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - liquid_pluralize
  - liquid_reading_time


# Github settings
repository: team-vrock/team-vrock.github.io
github: [metadata]